const unicorns = [
    {
        id: 1,
        name: 'Baby',
        birthyear: new Date().getFullYear(),
        weight: 10,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-1.jpg',
        hobbies: ['Sleep', 'Cry'],
        capacities: [1, 2],
    },
    {
        id: 2,
        name: 'Dylan',
        birthyear: new Date().getFullYear() - 1,
        weight: 32,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-2.jpg',
        hobbies: ['Coffee', 'Sing', 'Cinema'],
        capacities: [1],
    },
    {
        id: 3,
        name: 'Charly',
        birthyear: new Date().getFullYear() - 12,
        weight: 45,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-3.png',
        hobbies: ['Read', 'Photography'],
        capacities: [2],
    },
    {
        id: 4,
        name: 'John',
        birthyear: new Date().getFullYear() - 17,
        weight: 54,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-4.jpg',
        hobbies: ['Sport', 'Music'],
        capacities: [],
    },
    {
        id: 5,
        name: 'Freddy',
        birthyear: new Date().getFullYear() - 49,
        weight: 90,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-5.jpg',
        hobbies: ['Cut wood', 'Hockey'],
        capacities: [3],
    },
    {
        id: 6,
        name: 'Cindy',
        birthyear: new Date().getFullYear() - 15,
        weight: 46,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-6.jpg',
        hobbies: ['Vampire Diaries', 'Gossip Girl', 'Justin Bieber', 'One Direction'],
        capacities: [1, 2, 3],
    },
    {
        id: 7,
        name: 'Hervé',
        birthyear: new Date().getFullYear() - 9,
        weight: 21,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-7.jpg',
        hobbies: ['Drink', 'Football', 'cycling'],
        capacities: [3],
    },
    {
        id: 8,
        name: 'Christian',
        birthyear: new Date().getFullYear() - 35,
        weight: 75,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-8.png',
        hobbies: ['Horsing', 'Gymnastic', 'Parties'],
        capacities: [2, 4],
    },
    {
        id: 9,
        name: 'Gandalf',
        birthyear: new Date().getFullYear() - 150,
        weight: 65,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-9.png',
        hobbies: ['Dragons', 'Magic'],
        capacities: [4],
    },
    {
        id: 10,
        name: 'Donatello, Raphael, Michelangelo & leonardo',
        birthyear: new Date().getFullYear() - 21,
        weight: 300,
        photo: 'http://localhost:3000/unicorns/photos/unicorn-10.jpg',
        hobbies: ['Pizzas', 'Martial arts'],
        capacities: [1, 2],
    },
];

export default unicorns;
